[package]
name = "franz"
version = "0.1.0"
edition = "2021"
authors = ["Maxi Saparov <max.saparov@gmail.com>"]
description = "[WIP] a small, friendly, simple alternative to Apache Kafka"
documentation = "https://docs.rs/franz"
homepage = "https://github.com/MostlyMax/franz"
repository = "https://github.com/MostlyMax/franz"
readme = "README.md"
keywords = ["ringbuffer", "queue", "kafka"]
license = "MIT"
categories = ["ringbuffer"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
franz_macros = { path = "franz-macros" }
franz_core = { path = "franz-core" }
clap = { version = "4.5.8", features = ["derive"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
disk-ringbuffer = { git = "https://github.com/MostlyMax/disk-ringbuffer.git", branch = "maxi/doing-it-all" }
env_logger = "0.11.3"
futures = "0.3.30"
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.11", features = ["full"] }
tracing = "0.1.40"
memmap2 = "0.9.4"
